// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LogReq struct {
	Id     int64  `json:"id"`
	Action string `json:"action"`
}

type LogResp struct {
	Message string `json:"message"`
}
